<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \TSG\Surprise\Block\Item\Price\Renderer */
$_item = $block->getItem();
?>

<?php if (!$_item->getSurprise()) : ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtml(__('Excl. Tax')) ?>">
        <span class="cart-price">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getCalculationPrice()) ?>
        </span>
    </span>
<?php else:?>
<style>
    <?php echo "#cart-".$_item->getId()."-qty" ?> {
        visibility: hidden;
    }
</style>
<?php endif;?>
