<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/** @var $block \Magento\Checkout\Block\Item\Price\Renderer */
$_item = $block->getItem();
?>

<?php if ($_item === 'is_surprise') : ?>
<h1>Surprise</h1>
<?php else: ?>
    <span class="price-including-tax" data-label="<?= $block->escapeHtml(__('Excl. Tax')) ?>">
        <span class="cart-price">
            <?= /* @escapeNotVerified */ $this->helper('Magento\Checkout\Helper\Data')->formatPrice($_item->getCalculationPrice()) ?>
        </span>
    </span>
<?php endif;?>
