<?php /**
* Surprise DropDown template
*
* @var $block \TSG\Surprise\Model\ResourceModel\Product\Collection
*/?>
<?php

$visibleBlock = $block->isVisible();
$_surpriseCollection = $block->getSurpriseCollection();

?>
<?php if (count($_surpriseCollection) > 0 && $visibleBlock): ?>
<div class="control">
    <select name="surprise_product" form="product_addtocart_form">
        <option value="" selected="selected">Choose a surprise</option>
        <?php  foreach ($_surpriseCollection as $item): ?>
        <option value="<?=$item->getEntityId(); ?>"><?= $item->getName(); ?></option>
        <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>