<?php /**
* Surprise DropDown template
*
* @var $block \Magento\Catalog\Model\ResourceModel\Product\Collection
*/?>
<?php $_surpriseCollection = $block->getSurpriseCollection(); ?>
<div class="control">
    <select name="related_product" form="product_addtocart_form">
        <option value="null" selected="selected">Choose a surprise</option>
        <?php  foreach ($_surpriseCollection as $item): ?>
        <option value="<?=$item->getEntityId(); ?>"><?= $item->getName(); ?></option>
        <?php endforeach; ?>
    </select>
</div>