<?php

namespace TSG\Surprise\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
// use Magento\Framework\Model\AbstractModel;

class SurpriseStatResource extends AbstractDb
{

    protected function _construct()
    {
        $this->_init('tsg_product_surprise', 'entity_id');
    }

    public function save(\Magento\Framework\Model\AbstractModel $object)
    {
        return parent::save($object);
    }

    public function delete(\Magento\Framework\Model\AbstractModel $object)
    {
        return parent::delete($object); // TODO: Change the autogenerated stub
    }

    public function load(\Magento\Framework\Model\AbstractModel $object, $value, $field = null)
    {
        return parent::load($object, $value, $field); // TODO: Change the autogenerated stub
    }

    public function beforeSave(\Magento\Framework\DataObject $object)
    {

        parent::beforeSave($object); // TODO: Change the autogenerated stub
    }


}